// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic-service.proto

package com.dependency.mscore.grpc.config;

public final class GenericServiceOuterClass {
  private GenericServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dependency_mscore_grpc_config_GenericRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dependency_mscore_grpc_config_GenericRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dependency_mscore_grpc_config_GenericResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dependency_mscore_grpc_config_GenericResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025generic-service.proto\022!com.dependency." +
      "mscore.grpc.config\032\031google/protobuf/any." +
      "proto\"4\n\016GenericRequest\022\"\n\004data\030\001 \001(\0132\024." +
      "google.protobuf.Any\"5\n\017GenericResponse\022\"" +
      "\n\004data\030\001 \001(\0132\024.google.protobuf.Any2\177\n\016Ge" +
      "nericService\022m\n\004call\0221.com.dependency.ms" +
      "core.grpc.config.GenericRequest\0322.com.de" +
      "pendency.mscore.grpc.config.GenericRespo" +
      "nseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_dependency_mscore_grpc_config_GenericRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dependency_mscore_grpc_config_GenericRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dependency_mscore_grpc_config_GenericRequest_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_dependency_mscore_grpc_config_GenericResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dependency_mscore_grpc_config_GenericResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dependency_mscore_grpc_config_GenericResponse_descriptor,
        new java.lang.String[] { "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
